### ISSUE TITLE
Discord Steam Verification

### ISSUE THREAD

**Issue by rjdXpxigYxNT** [leighmacdonald/gbans#501]
Use the set steam command as a way to verify discord members.

**Comment by leighmacdonald** [comment]
That command is really only meant for trusted staff members (#38 adds some basic discord user id tracking for users). It was just a stop gap solution because i didn't want to go through the process of getting the proper authentication dance up at the time: https://discord.com/developers/docs/topics/oauth2 . `set_steam` has no checks or balances so it just blindly trusts the user is who they say they are, which is very much not ideal. 

Using the real discord oauth setup would force people to use their *actual* discord accounts, redirecting them to discord.com to login, basically exactly how they login to steam as well. This would ensure that they are the actual owners of the linked accounts.  

Its certainly something i would like to see happen.

**Comment by leighmacdonald** [comment]
Was enabled in #541 along with patreon connection type.
